### ISSUE TITLE
Detection works, Mouse input doesn't for me 

### ISSUE THREAD

**Issue by t-nshi** [McDaived/AIMi#11]
Is there any variables I can change? Like sens, dpi, etc that I'm missing?

**Comment by McDaived** [comment]
if you use it on valorant it dosent work cuz you need a driver kernal to bypass it, and if not work in any game you should disable raw input mouse in game you test aimi on it, and disable enhance pointer . 

**important:** 

disable **raw input** in any game you want play.
disable **enhance pointer** :  Mouse Properties->Pointer Options->Enhance Pointer Precision

in a few updates i will make config file to aimi to control with smoothness and some variables .
thx for feedback, 

**If there is another question, dont hesitate to let me know and reopen the issue**
