### ISSUE TITLE
ERROR VİDEO REC:001

### ISSUE THREAD

**Issue by Kaira3535** [McDaived/AIMi#13]
As you can see, when you press esc, the mouse goes to the character's head, but when you return to the game, there is only a vibration, it is ridiculous, but it does not move the mouse in the game, it only vibrates when you see the character, the reason why I press esc in the video is that when I press esc, it takes the mouse directly to the man's head, but it does not move in the game, it only vibrates when it enters the character area.

VİDEO: https://streamable.com/fkbvhx

**Comment by McDaived** [comment]
reduce mouse sensitivity, i recommend cs2: game sens 1.82 and use dpi 1600

Disable enhance pointer : Mouse Properties->Pointer Options->Enhance Pointer Precision

what version of Python did you install, and did it work in the old version? When did this problem appear?
what type of mouse are you using?

**Comment by Kaira3535** [comment]
Enchange pointer is already disabled since the day I installed this system I use the same mouse Logitech g502 Python3.9 and Python3.10 I tried both versions

**Comment by Kaira3535** [comment]
> reduce mouse sensitivity, i recommend cs2: game sens 1.82 and use dpi 1600
> 
> Disable enhance pointer : Mouse Properties->Pointer Options->Enhance Pointer Precision
> 
> what version of Python did you install, and did it work in the old version? When did this problem appear? what type of mouse are you using?
Enchange pointer is already disabled since the day I installed this system I use the same mouse Logitech g502 Python3.9 and Python3.10 I tried both versions
?

**Comment by McDaived** [comment]
install latest version of python 3.12 and test it..

 in next version i will add new features like mouse sens , and smoothness , auto shoot , etc .
very soon i will fix everything to make it better, i will keep every bugs and error in my mind and fix it.
please keep me informed about these matters so that i can improve it to make it good for use in all games.

**Comment by Kaira3535** [comment]
I tried python 3.12 and the same error persists
