### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by peer-pri** [McDaived/AIMi#24]
Exception has occurred: FileNotFoundError
[Errno 2] No such file or directory: 'models\\coco-dataset.labels'
  File "PRIVATE/AIMi-main\lib\detect.py", line 51, in aimbot
    LABELS = open(labelsPath).read().strip().split("\n")
             ^^^^^^^^^^^^^^^^
  File "PRIVATE\AIMi-main\start.py", line 20, in <module>
    inputs.aimbot(ENABLE_AIMBOT=True)
FileNotFoundError: [Errno 2] No such file or directory: 'models\\coco-dataset.labels'

**Comment by peer-pri** [comment]
Fixed

**Comment by DeadAreser** [comment]
> Fixed

How did you do that?
