### ISSUE TITLE
Smart AI ?

### ISSUE THREAD

**Issue by Kaira3535** [McDaived/AIMi#4]
Can you include an adjustable smart AI logic in AIMi again? For instance, if I were to give an example, for use in a game like CS2, config, etc. If you can do this, it would really be excellent.

![image](https://github.com/McDaived/AIMi/assets/76821732/75d000ab-d362-4843-b83c-835faaad9e1a)

**Comment by McDaived** [comment]
That would be really useful, but now I'm working on improving it to make it look better, **i'll keep your opinion in mind**. Thank you.
