### ISSUE TITLE
Start.py won't start

### ISSUE THREAD

**Issue by prawnhitter** [McDaived/AIMi#7]
Hi, i wanted to start your python script, but it won't start.

So i tried to run it in IDLE and do get this:

Python 3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

= RESTART: C:\Users\[...]\Desktop\AIMi-main\start.py
Traceback (most recent call last):
  File "C:\Users\[...]\Desktop\AIMi-main\start.py", line 3, in <module>
    subprocess.call(["pip", "install", "-r", "assets/requirements.txt"])
  File "C:\Users\[...]\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 389, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\[...]\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\[...]\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden

Can you help me what is missing to run your script?

**Comment by McDaived** [comment]
${\color{red}PS:}$ **If you run the program and it closes immediately, please take the following**

***Download latest version of python then install it like this pictures..***

<img src="https://i.imgur.com/t8BNihH.png" alt="Your Image Description" width="500"><img src="https://i.imgur.com/eW0TQ3B.png" alt="Your Image Description" width="500"><img src="https://i.imgur.com/fuvAhvg.png" alt="Your Image Description" width="500">
